---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saml.tickletechnologies.com
  resources:
  - appintegrations
  - spinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saml.tickletechnologies.com
  resources:
  - appintegrations/finalizers
  - spinstances/finalizers
  verbs:
  - update
- apiGroups:
  - saml.tickletechnologies.com
  resources:
  - appintegrations/status
  - spinstances/status
  verbs:
  - get
  - patch
  - update
